name: retsupp_cpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # Scientific stack
  - numpy<2.0
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - ipywidgets
  - pingouin
  # Neuroimaging
  - nibabel
  - nilearn
  - nipype
  # Install via pip for CPU-only on cluster
  - pip:
      - tensorflow-cpu==2.14.0
      - tensorflow-probability==0.22.0
      - protobuf==3.20.3
      - tqdm
      - pybids
      - pymc
      - git+https://github.com/cvnlab/GLMsingle.git
      - -e ./libs/braincoder
      - -e .
